DispatchScreenStats/Areas/ScreenStats/Controllers/ScreenRecIFrameController.cs
using System;
using System.Collections.Generic;
using System.Collections.Specialized;
using System.Linq;
using System.Linq.Expressions;
using System.Text.RegularExpressions;
using System.Web.Mvc;
using DispatchScreenStats.Controllers;
using DispatchScreenStats.IRepository;
using DispatchScreenStats.Models;
using DispatchScreenStats.Repository;
using FineUIMvc;
using MongoDB.Bson;
using MongoDB.Driver;
using Newtonsoft.Json.Linq;

namespace DispatchScreenStats.Areas.ScreenStats.Controllers
{
    public class ScreenRecIFrameController : BaseController
    {
        private readonly IMongoRepository<ScreenRec> _rep = new MongoRepository<ScreenRec>();
        private readonly Expression<Func<ScreenRec, bool>> _filter = t =>!t.IsLog;
        //
        // GET: /ScreenStats/ScreenRecIFrame/
        [OutputCache(Duration = 600)]
        public ActionResult Index()
        {
            int count;
            var list = _rep.QueryByPage(0, PageSize, out count,_filter);
            ViewBag.RecordCount = count;
            ViewBag.PageSize = PageSize;
            return View(list);
        }

        private void UpdateGrid(NameValueCollection values)
        {
            var fields = JArray.Parse(values["Grid1_fields"]);
            var pageIndex = Convert.ToInt32(values["Grid1_pageIndex"] ?? "0");
            var pageSize = Convert.ToInt32(values["Grid1_pageSize"] ?? "0");

            var devNum = values["tbDevNum"];
            var line = values["tbLine"];
            var owner = values["ddlOwner"] != null && values["ddlOwner"] != "[]" ? JArray.Parse(values["ddlOwner"]) : null;
            var station = values["tbStation"];
            var filter = new List<FilterDefinition<ScreenRec>> { _filter };
            if (!string.IsNullOrWhiteSpace(devNum))
            {
                filter.Add(Builders<ScreenRec>.Filter.Regex(t =>t.DeviceNum,
                    new BsonRegularExpression(new Regex(devNum.Trim(),RegexOptions.IgnoreCase))));
            }
            if (owner != null)
            {
                filter.Add(Builders<ScreenRec>.Filter.In(t => t.Owner, owner));
            }
            if (!string.IsNullOrWhiteSpace(station))
            {
                filter.Add(Builders<ScreenRec>.Filter.Regex(t => t.InstallStation,
                    new BsonRegularExpression(new Regex(station.Trim()))));
            }
            if (!string.IsNullOrWhiteSpace(line))
            {
                filter.Add(Builders<ScreenRec>.Filter.Regex(t => t.LineName,
                    new BsonRegularExpression(new Regex(line.Trim()))));
            }
            int count;
            var list = _rep.QueryByPage(pageIndex, pageSize, out count, filter.Any() ? Builders<ScreenRec>.Filter.And(filter) : null);
            var grid1 = UIHelper.Grid("Grid1");
            grid1.RecordCount(count);
            grid1.PageSize(pageSize);
            grid1.DataSource(list, fields);
        }
        public ActionResult DoSearch(FormCollection values)
        {
            UpdateGrid(values);
            return UIHelper.Result();
        }
	}
}

DispatchScreenStats/Areas/ScreenStats/Controllers/ScreenRepairsController.cs
using System;
using System.Collections.Generic;
using System.Collections.Specialized;
using System.IO;
using System.Linq;
using System.Linq.Expressions;
using System.Text;
using System.Text.RegularExpressions;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using DispatchScreenStats.Common;
using DispatchScreenStats.Controllers;
using DispatchScreenStats.Enums;
using DispatchScreenStats.IRepository;
using DispatchScreenStats.Models;
using DispatchScreenStats.Repository;
using FineUIMvc;
using MongoDB.Bson;
using MongoDB.Driver;
using Newtonsoft.Json.Linq;
using NPOI.HSSF.UserModel;
using NPOI.SS.UserModel;
using NPOI.XSSF.UserModel;

namespace DispatchScreenStats.Areas.ScreenStats.Controllers
{
    public class ScreenRepairsController : BaseController
    {
        private readonly IMongoRepository<ScreenRepairs> _rep = new MongoRepository<ScreenRepairs>();
        private readonly IMongoRepository<ScreenRecDetail> _repDetail = new MongoRepository<ScreenRecDetail>();
        private readonly IMongoRepository<Auth> _repAuth = new MongoRepository<Auth>();
        private readonly SortDefinition<ScreenRepairs> _sort = Builders<ScreenRepairs>.Sort.Ascending(t => t.Status).Descending(t=>t.RepairsDate);
        private readonly FilterDefinition<ScreenRepairs> _filterRange;
        private readonly bool _isAuth;
        public ScreenRepairsController()
        {
            var user = HttpUtility.UrlDecode(CommonHelper.User);
            if (user != "admin")
            {
                var auth = _repAuth.Get(t => t.UserId == int.Parse(CommonHelper.UserId));
                if (auth != null)
                {
                    var range = auth.Range;
                    if (range > 0)
                    {
                        _filterRange = Builders<ScreenRepairs>.Filter.Gte(t => t.RepairsDate,
                            DateTime.Today.AddDays(-range));
                    }
                    _isAuth = auth.Permission==1;
                }
            }
            else
            {
                _isAuth = true;
            }
        }
        public ActionResult Index()
        {
            int count;
            var list = _rep.QueryByPage(0, PageSize, out count, _filterRange, _sort);
            ViewBag.RecordCount = count;
            ViewBag.PageSize = PageSize;
            ViewBag.isAuth = _isAuth;
            return View(list);
        }
        public ActionResult AddOrEdit(int? id)
        {
            ViewBag.hTypes = _rep.Distinct(t => t.HitchType).Where(t=>!string.IsNullOrWhiteSpace(t)).Select(t => new ListItem(t, t)).ToArray();
            ViewBag.hStatuses =
            (from object e in Enum.GetValues(typeof(HitchStatusEnum))
                select new ListItem(e.ToString(), ((int) e).ToString())).ToArray();
           ViewBag.Accepters = _rep.Distinct(t => t.Accepter).Where(t => !string.IsNullOrWhiteSpace(t)).OrderBy(t => t).Select(t => new ListItem(t, t)).ToArray();
           ViewBag.Handlers = _rep.Distinct(t => t.Handler).Where(t => !string.IsNullOrWhiteSpace(t)).OrderBy(t => t).Select(t => new ListItem(t, t)).ToArray();
            ViewBag.isAuth = _isAuth;
            if (id == null) return View();
            var model = _rep.Get(t => t._id ==id);
            if (model == null)
            {
                return HttpNotFound();
            }
            return View(model);
        }
        [HttpPost]
        public ActionResult AddOrEdit(ScreenRepairs model)
        {
            try
            {
                var isStatusInput = Request["Status_isUserInput"];
                if (!string.IsNullOrEmpty(isStatusInput))
                {
                    model.Status = (HitchStatusEnum) Enum.Parse(typeof(HitchStatusEnum), Request["Status_text"]);
                }
                var isTypeInput = Request["HitchType_isUserInput"];
                if (!string.IsNullOrEmpty(isTypeInput))
                {
                    if (bool.Parse(isTypeInput))
                    {
                        model.HitchType = Request["HitchType_text"];
                    }
                }

                var isAccInput = Request["Accepter_isUserInput"];
                var isHandInput = Request["Handler_isUserInput"];
                if (!string.IsNullOrEmpty(isAccInput))
                {
                    model.Accepter = Request["Accepter_text"];
                }
                if (!string.IsNullOrEmpty(isHandInput))
                {
                    model.Handler = Request["Handler_text"];
                }
                //处理上传附件
                var file = Request.Files["file"];
                if (file != null && file.ContentLength != 0)
                {
                    var fileName = file.FileName;
                    var fileType = GetFileType(fileName);
                    if (!ValidFileTypes.Contains(fileType))
                    {
                        // 清空文件上传组件
                        UIHelper.FileUpload("file").Reset();
                        ShowNotify("无效的文件类型！");
                    }
                    else
                    {
                        var md5 = file.InputStream.GetMd5();
                        var repairModel = _rep.Get(t => t.FileMd5 == md5);
                        if (repairModel != null)
                        {
                            model.FileName = repairModel.FileName;
                            model.FilePath = repairModel.FilePath;
                        }
                        else
                        {
                            var name = file.FileName;
                            if (_rep.Get(t => t.FileName == file.FileName) != null)
                            {
                                name = file.FileName + "_" + Guid.NewGuid();
                            }
                            var path = Server.MapPath("~/attachments");
                            if (!Directory.Exists(path))
                            {
                                Directory.CreateDirectory(path);
                            }
                            var attachPath = Path.Combine(path, name);
                            file.SaveAs(attachPath);
                            model.FileName = name;
                            model.FilePath = attachPath;
                        }
                        model.FileMd5 = md5;
                    }
                }

                if (model._id == 0)
                {
                        model._id = (int)(_rep.Max(t => t._id) ?? 0) + 1;
                        _rep.Add(model);
                        // 关闭本窗体（触发窗体的关闭事件）
                        PageContext.RegisterStartupScript(ActiveWindow.GetHidePostBackReference());
                }
                else
                {
                    _rep.Update(t => t._id == model._id,
                        Builders<ScreenRepairs>.Update.Set(t => t.RepairsDate, model.RepairsDate)
                            .Set(t => t.LineName, model.LineName)
                            .Set(t => t.Station, model.Station)
                            .Set(t => t.Owner, model.Owner)
                            .Set(t => t.RepairsSource, model.RepairsSource)
                            .Set(t => t.Accepter, model.Accepter)
                            .Set(t => t.Handler, model.Handler)
                            .Set(t => t.HitchType, model.HitchType)
                            .Set(t => t.Status, model.Status)
                            .Set(t => t.HitchContent, model.HitchContent)
                            .Set(t => t.Solution, model.Solution)
                            .Set(t=>t.FileName,model.FileName)
                            .Set(t=>t.FileMd5,model.FileMd5)
                            .Set(t=>t.FilePath,model.FilePath));
                    // 关闭本窗体（触发窗体的关闭事件）
                    PageContext.RegisterStartupScript(ActiveWindow.GetHidePostBackReference());
                }
            }
            catch (Exception ex)
            {
                Alert.Show(ex.Message, MessageBoxIcon.Warning);
            }
            return UIHelper.Result();
        }

        public FileResult Download(int? id)
        {
            var model=_rep.Get(t=>t._id==id);
            //if (string.IsNullOrEmpty(model.FilePath))
            //{
            //    Alert.Show("无附件", MessageBoxIcon.Warning);
            //    return UIHelper.Result();
            //}
            return File(System.IO.File.OpenRead(model.FilePath), "application/excel", model.FileName);
        }

        private void UpdateGrid(NameValueCollection values)
        {
            var fields = JArray.Parse(values["Grid1_fields"]);
            var pageIndex = Convert.ToInt32(values["Grid1_pageIndex"] ?? "0");
            var pageSize = Convert.ToInt32(values["Grid1_pageSize"] ?? "0");

            var owner = values["ddlOwner"] != null && values["ddlOwner"] != "[]" ? JArray.Parse(values["ddlOwner"]) : null;
            var line = values["tbLine"];
            var isFuzzyLine = values["cbIsFuzzyLine"];
            var station = values["tbStation"];
            var isFuzzyStation = values["cbIsFuzzyStation"];
            var tbAccepter = values["tbAccepter"];
            var tbHandler = values["tbHandler"];
            var tbType = values["tbType"];
            var tbStatus = values["tbStatus"];
            var date = values["tbDate"];

            var filter = new List<FilterDefinition<ScreenRepairs>>();
            if (_filterRange != null) filter.Add(_filterRange);

            if (!string.IsNullOrWhiteSpace(tbAccepter))
            {
                filter.Add(Builders<ScreenRepairs>.Filter.Eq(t => t.Accepter, tbAccepter));
            }
            if (!string.IsNullOrWhiteSpace(tbHandler))
            {
                filter.Add(Builders<ScreenRepairs>.Filter.Eq(t => t.Handler, tbHandler));
            }
            if (!string.IsNullOrWhiteSpace(tbType))
            {

DispatchScreenStats/Areas/ScreenStats/Views/ScreenRepairs/AddOrEdit.cshtml
@{
    var F = Html.F();
    var isAuth = ViewBag.isAuth;
}

@using DispatchScreenStats.Common
@model ScreenRepairs

@section body {
    @if (Model == null)
    {
        @(F.Panel()
              .ID("Panel1")
              .ShowBorder(false)
              .ShowHeader(false)
              .BodyPadding(10)
              .AutoScroll(true)
              .IsViewPort(true)
              .Toolbars(
                  F.Toolbar()
                      .Items(
                          F.Button()
                              .Icon(Icon.SystemClose)
                              .Text("关闭")
                              .Listener("click", "F.activeWindow.hide();"),
                          F.ToolbarSeparator(),
                       F.Button()
                                      .ValidateForms("SimpleForm1")
                                      .Icon(Icon.SystemSaveClose)
                                      .OnClick(Url.Action("AddOrEdit"), "SimpleForm1")
                                      .Text("保存后关闭")
                      )
              )
              .Items(
                  F.SimpleForm()
                      .ID("SimpleForm1")
                      .ShowBorder(false)
                      .ShowHeader(false)
                      .Items(
                          F.DatePickerFor(m => m.RepairsDate).SelectedDate(DateTime.Today	),
                          F.TriggerBoxFor(m => m.LineName).TriggerIcon(TriggerIcon.Search).EnableEdit(false).OnClientTriggerClick("onTriggerClick"),
                          F.TextBoxFor(m => m.Station).Enabled(false),
                          F.TextBoxFor(t => t.Owner).Enabled(false),
                          F.HiddenFieldFor(t=>t.DeviceNum),
                          F.TextBoxFor(t => t.RepairsSource),
                              isAuth ? F.DropDownListFor(t => t.Accepter).Text(HttpUtility.UrlDecode(CommonHelper.UserName)).AutoSelectFirstItem(false).EnableEdit(true).ForceSelection(false).Items(ViewBag.Accepters) : F.TextBoxFor(t => t.Accepter).Enabled(false).Text(HttpUtility.UrlDecode(CommonHelper.UserName)),
                          F.DropDownListFor(t => t.Handler).AutoSelectFirstItem(false).EnableEdit(true).ForceSelection(false).Items(ViewBag.Handlers),
                          F.DropDownListFor(t => t.HitchType).AutoSelectFirstItem(false).EnableEdit(true).ForceSelection(false).Items(ViewBag.hTypes),
                          F.DropDownListFor(t => t.Status).Items(ViewBag.hStatuses),
                          F.TextAreaFor(t => t.HitchContent),
                          F.TextAreaFor(m => m.Solution),
                          F.FileUpload()
                              .ID("file")
                              .EmptyText("请选择文件")
                              .Label("上传附件")
                      )
              ))
    }
    else
    {
          @(F.Panel()
          .ID("Panel1")
          .ShowBorder(false)
          .ShowHeader(false)
          .BodyPadding(10)
          .AutoScroll(true)
          .IsViewPort(true)
          .Toolbars(
              F.Toolbar()
                  .Items(
                      F.Button()
                          .Icon(Icon.SystemClose)
                          .Text("关闭")
                          .Listener("click", "F.activeWindow.hide();"),
                      F.ToolbarSeparator(),
                   F.Button()
                                  .ValidateForms("SimpleForm1")
                                  .Icon(Icon.SystemSaveClose)
                                  .OnClick(Url.Action("AddOrEdit"), "SimpleForm1")
                                    .Text("保存后关闭"),
                                                F.Button().Text("处理中").OnClick(Url.Action("OnHandle") + "?op=on"),
                                            F.Button().Text("已完成").OnClick(Url.Action("OnHandle") + "?op=done")
                  )
          )
          .Items(
              F.SimpleForm()
                  .ID("SimpleForm1")
                  .ShowBorder(false)
                  .ShowHeader(false)
                  .Items(
                      F.HiddenFieldFor(m => m._id),
                      F.DatePickerFor(m => m.RepairsDate),
                      F.TriggerBoxFor(m => m.LineName).TriggerIcon(TriggerIcon.Search).EnableEdit(false).OnClientTriggerClick("onTriggerClick"),
                      F.TextBoxFor(m => m.Station).Enabled(false),
                      F.TextBoxFor(t => t.Owner).Enabled(false),
                      F.HiddenFieldFor(t=>t.DeviceNum),
                      F.TextBoxFor(t => t.RepairsSource),
        F.DropDownListFor(t => t.Accepter).AutoSelectFirstItem(false).EnableEdit(true).ForceSelection(false).Items(ViewBag.Accepters),
                                      F.DropDownListFor(t => t.Handler).AutoSelectFirstItem(false).EnableEdit(true).ForceSelection(false).Items(ViewBag.Handlers),
                              F.DropDownListFor(t => t.HitchType).AutoSelectFirstItem(false).EnableEdit(true).ForceSelection(false).Items(ViewBag.hTypes),
                              F.DropDownListFor(t => t.Status).Items(ViewBag.hStatuses),
                      F.TextAreaFor(t => t.HitchContent),
                      F.TextAreaFor(m => m.Solution),
                              F.FileUpload()
                        .ID("file")
                        .EmptyText("请选择文件")
                        .Label("上传附件")
                  )
          ))
    }
  


    @(F.Window()
          .ID("Window1")
          .Width(700)
          .Height(450)
          .IsModal(true)
          .Hidden(true)
          .Target(Target.Top)
          .EnableResize(true)
          .EnableMaximize(true)
          .EnableIFrame(true)
          .IFrameUrl(Url.Content("about:blank"))
          )
}
@section script{
    <script>
        function onTriggerClick() {
            var iframeWindowUrl = '@Url.Action("Index","ScreenRecIFrame","选择")';
            F.ui.Window1.show(iframeWindowUrl, "选择");
        }
        function updateGridRow(rowId, values) {
            F.ui.LineName.setValue(values['LineName']);
            F.ui.Station.setValue(values['Station']);
            F.ui.Owner.setValue(values['Owner']);
            F.ui.DeviceNum.setValue(values['DeviceNum']);
        }
    </script>
}

DispatchScreenStats/Areas/ScreenStats/Views/ScreenRepairs/RepairsImport.cshtml
@{
    var F = @Html.F();
}
@section body {
    @(F.SimpleForm()
        .ID("SimpleForm1")
        .BodyPadding(5)
        .Width(550)
        .EnableCollapse(true)
        .ShowBorder(true)
        .ShowHeader(false)
        .Items(
            F.FileUpload()
                .ID("file")
                .EmptyText("请选择Excel文件")
                .Label("文件")
                .Required(true)
                .ShowRedStar(true),
            F.Button()
                .ID("btnSubmit")
                                        .OnClick(Url.Content("~/ScreenStats/ScreenRepairs/RepairsImport"), "SimpleForm1")
                .ValidateForms("SimpleForm1")
                .Text("导入")
        )
    )
}
